// GENERATED by web/scripts/build_news_sample.py from one saved snapshot of r/nrl's RSS feed.
// Titles, links and times are real; flairs are guessed from the titles. No usernames are kept.

import type { NewsPost } from "./news";

export const SNAPSHOT_AT = "2026-10-10T11:59:50+00:00";

export const SAMPLE_NEWS: NewsPost[] = [
  {
    "id": "t3_1x26dp9",
    "title": "Jonah Pezet primed for fresh Broncos start after ‘naive’ Eels gap-year",
    "link": "https://www.reddit.com/r/nrl/comments/1x26dp9/jonah_pezet_primed_for_fresh_broncos_start_after/",
    "domain": "dailytelegraph.com.au",
    "published": "2026-10-10T04:47:52+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x26ct6",
    "title": "From remote islands to the Bulldogs: Inside the Silktails pathway",
    "link": "https://www.reddit.com/r/nrl/comments/1x26ct6/from_remote_islands_to_the_bulldogs_inside_the/",
    "domain": "nrl.com",
    "published": "2026-10-10T04:46:29+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x1x6ck",
    "title": "Club Statement: Helloworld Stadium completion",
    "link": "https://www.reddit.com/r/nrl/comments/1x1x6ck/club_statement_helloworld_stadium_completion/",
    "domain": "penrithpanthers.com.au",
    "published": "2026-10-09T21:12:37+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x1tce3",
    "title": "Saturday Off Topic Thread",
    "link": "https://www.reddit.com/r/nrl/comments/1x1tce3/saturday_off_topic_thread/",
    "domain": null,
    "published": "2026-10-09T18:41:04+00:00",
    "flair": "Daily thread"
  },
  {
    "id": "t3_1x1tbhs",
    "title": "Saturday Random Footy Talk Thread",
    "link": "https://www.reddit.com/r/nrl/comments/1x1tbhs/saturday_random_footy_talk_thread/",
    "domain": null,
    "published": "2026-10-09T18:40:08+00:00",
    "flair": "Daily thread"
  },
  {
    "id": "t3_1x1hfyx",
    "title": "Perth Bears CEO Anthony De Ceglie to leave club",
    "link": "https://www.reddit.com/r/nrl/comments/1x1hfyx/perth_bears_ceo_anthony_de_ceglie_to_leave_club/",
    "domain": "abc.net.au",
    "published": "2026-10-09T10:05:47+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x1goz6",
    "title": "NRL boss Peter V’landys reveals plans for 22 team competition by 2035",
    "link": "https://www.reddit.com/r/nrl/comments/1x1goz6/nrl_boss_peter_vlandys_reveals_plans_for_22_team/",
    "domain": "dailytelegraph.com.au",
    "published": "2026-10-09T09:18:46+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x1gi5k",
    "title": "Perth Bears CEO Anthony De Ceglie steps down on the eve of club’s first pre-season",
    "link": "https://www.reddit.com/r/nrl/comments/1x1gi5k/perth_bears_ceo_anthony_de_ceglie_steps_down_on/",
    "domain": "dailytelegraph.com.au",
    "published": "2026-10-09T09:06:51+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x1g2hz",
    "title": "Titans star’s $900k contract ‘lie’ as agent-media war explodes — CODE Sports",
    "link": "https://www.reddit.com/r/nrl/comments/1x1g2hz/titans_stars_900k_contract_lie_as_agentmedia_war/",
    "domain": "apple.news",
    "published": "2026-10-09T08:39:06+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x1dlml",
    "title": "Tedesco lays out plan for Roosters swansong",
    "link": "https://www.reddit.com/r/nrl/comments/1x1dlml/tedesco_lays_out_plan_for_roosters_swansong/",
    "domain": "smh.com.au",
    "published": "2026-10-09T06:01:36+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x1bnma",
    "title": "NRL 2026: Cameron Munster could play for a Sydney club after Melbourne Storm",
    "link": "https://www.reddit.com/r/nrl/comments/1x1bnma/nrl_2026_cameron_munster_could_play_for_a_sydney/",
    "domain": "smh.com.au",
    "published": "2026-10-09T04:09:00+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x19v9a",
    "title": "Knights recruiter Peter O’Sullivan agrees to $2.5m mega deal with Broncos",
    "link": "https://www.reddit.com/r/nrl/comments/1x19v9a/knights_recruiter_peter_osullivan_agrees_to_25m/",
    "domain": "i.redd.it",
    "published": "2026-10-09T02:35:01+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x18xii",
    "title": "Grant linked with bombshell move north; Kangaroos star drops huge hint on future — Whispers",
    "link": "https://www.reddit.com/r/nrl/comments/1x18xii/grant_linked_with_bombshell_move_north_kangaroos/",
    "domain": "foxsports.com.au",
    "published": "2026-10-09T01:47:36+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x14qu6",
    "title": "Parramatta Eels appoint Mike Rush as Chief Executive Officer",
    "link": "https://www.reddit.com/r/nrl/comments/1x14qu6/parramatta_eels_appoint_mike_rush_as_chief/",
    "domain": "parraeels.com.au",
    "published": "2026-10-08T22:27:20+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x11nou",
    "title": "Nathan Cleary's Dally M Medal highlight reel: 2026 Season | NRL on Nine",
    "link": "https://www.reddit.com/r/nrl/comments/1x11nou/nathan_clearys_dally_m_medal_highlight_reel_2026/",
    "domain": "youtu.be",
    "published": "2026-10-08T20:21:11+00:00",
    "flair": "Media"
  },
  {
    "id": "t3_1x0z5at",
    "title": "Friday Serious Discussion Thread",
    "link": "https://www.reddit.com/r/nrl/comments/1x0z5at/friday_serious_discussion_thread/",
    "domain": null,
    "published": "2026-10-08T18:46:19+00:00",
    "flair": "Daily thread"
  },
  {
    "id": "t3_1x0z0eu",
    "title": "Friday Off Topic Thread",
    "link": "https://www.reddit.com/r/nrl/comments/1x0z0eu/friday_off_topic_thread/",
    "domain": null,
    "published": "2026-10-08T18:41:05+00:00",
    "flair": "Daily thread"
  },
  {
    "id": "t3_1x0yzhz",
    "title": "Friday Random Footy Talk Thread",
    "link": "https://www.reddit.com/r/nrl/comments/1x0yzhz/friday_random_footy_talk_thread/",
    "domain": null,
    "published": "2026-10-08T18:40:08+00:00",
    "flair": "Daily thread"
  },
  {
    "id": "t3_1x0o89q",
    "title": "Parramatta have appointed former St Helens boss Mike Rush as their new chief executive.",
    "link": "https://www.reddit.com/r/nrl/comments/1x0o89q/parramatta_have_appointed_former_st_helens_boss/",
    "domain": "i.redd.it",
    "published": "2026-10-08T11:15:40+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x0imuh",
    "title": "Reece Walsh praises Roosters counterpart James Tedesco ahead of battle for Kangaroos No.1 jersey",
    "link": "https://www.reddit.com/r/nrl/comments/1x0imuh/reece_walsh_praises_roosters_counterpart_james/",
    "domain": "smh.com.au",
    "published": "2026-10-08T05:24:24+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x0i0bk",
    "title": "NZ Rugby launches court bid to protect 'Chiefs' name from PNG league franchise",
    "link": "https://www.reddit.com/r/nrl/comments/1x0i0bk/nz_rugby_launches_court_bid_to_protect_chiefs/",
    "domain": "abc.net.au",
    "published": "2026-10-08T04:48:30+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x0fexa",
    "title": "Berry re-signed by One New Zealand Warriors for 2027",
    "link": "https://www.reddit.com/r/nrl/comments/1x0fexa/berry_resigned_by_one_new_zealand_warriors_for/",
    "domain": "warriors.kiwi",
    "published": "2026-10-08T02:30:04+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x0expb",
    "title": "Spencer Leniu joins the Eels",
    "link": "https://www.reddit.com/r/nrl/comments/1x0expb/spencer_leniu_joins_the_eels/",
    "domain": "parraeels.com.au",
    "published": "2026-10-08T02:05:53+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x0che0",
    "title": "NZ Rugby files legal action over NRL expansion side's name",
    "link": "https://www.reddit.com/r/nrl/comments/1x0che0/nz_rugby_files_legal_action_over_nrl_expansion/",
    "domain": "1news.co.nz",
    "published": "2026-10-08T00:04:45+00:00",
    "flair": "News"
  },
  {
    "id": "t3_1x0bmdf",
    "title": "Roosters farewell Premiership winner Spencer Leniu",
    "link": "https://www.reddit.com/r/nrl/comments/1x0bmdf/roosters_farewell_premiership_winner_spencer_leniu/",
    "domain": "roosters.com.au",
    "published": "2026-10-07T23:24:28+00:00",
    "flair": "News"
  }
];
