"""Builds web/lib/sample-news.ts from one saved snapshot of r/nrl's public RSS feed.

Usage (from the repo root):  python -I web/scripts/build_news_sample.py <path-to-saved-feed.rss>

Keeps only each post's id, title, link, linked site and time: no usernames or post bodies. The RSS
feed has no flair, so the sample guesses one from the title (labelled as guessed on the
page); live, the Reddit API supplies the real flair (PLAN_WEB.md §3.6).
"""

import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "web" / "lib" / "sample-news.ts"
NS = {"a": "http://www.w3.org/2005/Atom"}


def guess_flair(title: str) -> str:
    if re.search(r"\bThread$", title):
        return "Daily thread"
    if re.search(r"highlight|video|\bon Nine\b|podcast", title, re.I):
        return "Media"
    return "News"


root = ET.parse(sys.argv[1]).getroot()
fetched = root.find("a:updated", NS).text
posts = []
for e in root.findall("a:entry", NS):
    link = e.find("a:link", NS).attrib["href"]
    if not link.startswith("https://www.reddit.com/r/nrl/"):
        continue  # only the subreddit's own threads
    title = e.find("a:title", NS).text.strip()
    # The site a link post points to (the feed's "[link]" anchor); none for text posts.
    m = re.search(r'<a href="https?://(?:www\.)?([^/"]+)[^"]*">\[link\]</a>', e.find("a:content", NS).text or "")
    domain = m.group(1) if m and "reddit.com" not in m.group(1) else None
    posts.append({"id": e.find("a:id", NS).text, "title": title, "link": link, "domain": domain,
                  "published": e.find("a:published", NS).text, "flair": guess_flair(title)})
posts.sort(key=lambda p: p["published"], reverse=True)

OUT.write_text(f"""// GENERATED by web/scripts/build_news_sample.py from one saved snapshot of r/nrl's RSS feed.
// Titles, links and times are real; flairs are guessed from the titles. No usernames are kept.

import type {{ NewsPost }} from "./news";

export const SNAPSHOT_AT = {json.dumps(fetched)};

export const SAMPLE_NEWS: NewsPost[] = {json.dumps(posts, indent=2, ensure_ascii=False)};
""", encoding="utf-8")
print(f"wrote {OUT.relative_to(ROOT)}: {len(posts)} posts, " + ", ".join(f"{f} {sum(p['flair'] == f for p in posts)}" for f in sorted({p['flair'] for p in posts})))
